# Generated by Django 5.0.2 on 2025-04-28 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metro', '0003_foodcategory_restaurant_categories'),
    ]

    operations = [
        migrations.CreateModel(
            name='StationID',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station_name', models.CharField(max_length=100)),
                ('line_name', models.CharField(max_length=100)),
                ('station_id', models.CharField(max_length=20, unique=True)),
            ],
        ),
    ]
