# Generated by Django 5.0.2 on 2025-05-27 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metro', '0005_metrofirstlasttrain'),
    ]

    operations = [
    ]
