# Generated by Django 5.0.2 on 2025-09-20 08:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metro', '0008_barcategory_bar_barreview_barbusinesshours'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('like', '喜歡'), ('favorite', '收藏'), ('comment', '評論')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
                ('review', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='metro.checkinreview')),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sent_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '通知',
                'verbose_name_plural': '通知',
                'db_table': 'metro_notification',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CheckinReviewFavorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='metro.checkinreview')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkin_favorites', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '打卡評論收藏',
                'verbose_name_plural': '打卡評論收藏',
                'db_table': 'metro_checkinreviewfavorite',
                'unique_together': {('review', 'user')},
            },
        ),
        migrations.CreateModel(
            name='CheckinReviewLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='metro.checkinreview')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkin_likes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '打卡評論喜歡',
                'verbose_name_plural': '打卡評論喜歡',
                'db_table': 'metro_checkinreviewlike',
                'unique_together': {('review', 'user')},
            },
        ),
    ]
