# Generated by Django 5.1.7 on 2025-03-08 10:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('google_place_id', models.CharField(max_length=255, unique=True, verbose_name='Google Place ID')),
                ('name', models.CharField(max_length=255, verbose_name='商家名稱')),
                ('address', models.CharField(max_length=255, verbose_name='地址')),
                ('latitude', models.DecimalField(decimal_places=7, max_digits=10, verbose_name='緯度')),
                ('longitude', models.DecimalField(decimal_places=7, max_digits=10, verbose_name='經度')),
                ('phone', models.CharField(blank=True, max_length=50, null=True, verbose_name='電話')),
                ('website', models.URLField(blank=True, null=True, verbose_name='網站')),
                ('rating', models.DecimalField(decimal_places=1, max_digits=2, null=True, verbose_name='評分')),
                ('rating_count', models.IntegerField(default=0, verbose_name='評分數量')),
                ('business_status', models.CharField(max_length=50, verbose_name='營業狀態')),
                ('types', models.JSONField(verbose_name='商家類型')),
                ('opening_hours', models.JSONField(null=True, verbose_name='營業時間')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='最後更新時間')),
            ],
            options={
                'verbose_name': '商家',
                'verbose_name_plural': '商家',
            },
        ),
        migrations.CreateModel(
            name='BusinessPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_reference', models.CharField(max_length=255, verbose_name='Google 相片參考ID')),
                ('photo_url', models.URLField(verbose_name='相片網址')),
                ('width', models.IntegerField(verbose_name='寬度')),
                ('height', models.IntegerField(verbose_name='高度')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='users.business')),
            ],
            options={
                'verbose_name': '商家相片',
                'verbose_name_plural': '商家相片',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=255, verbose_name='評論者名稱')),
                ('rating', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], verbose_name='評分')),
                ('text', models.TextField(verbose_name='評論內容')),
                ('time', models.DateTimeField(verbose_name='評論時間')),
                ('language', models.CharField(blank=True, max_length=10, null=True, verbose_name='語言')),
                ('google_review_id', models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='Google 評論 ID')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='users.business')),
            ],
            options={
                'verbose_name': '評論',
                'verbose_name_plural': '評論',
                'ordering': ['-time'],
            },
        ),
    ]
