# Generated by Django 5.1.7 on 2025-03-08 10:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_business_businessphoto_review'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetroLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='線路代碼')),
                ('name', models.CharField(max_length=50, verbose_name='線路名稱')),
                ('color', models.CharField(max_length=7, verbose_name='線路顏色')),
            ],
            options={
                'verbose_name': '捷運線',
                'verbose_name_plural': '捷運線',
            },
        ),
        migrations.AddField(
            model_name='business',
            name='distance_to_station',
            field=models.IntegerField(null=True, verbose_name='離車站距離(公尺)'),
        ),
        migrations.CreateModel(
            name='MetroStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, verbose_name='站點代碼')),
                ('name', models.CharField(max_length=50, verbose_name='站點名稱')),
                ('latitude', models.DecimalField(decimal_places=7, max_digits=10, verbose_name='緯度')),
                ('longitude', models.DecimalField(decimal_places=7, max_digits=10, verbose_name='經度')),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stations', to='users.metroline')),
            ],
            options={
                'verbose_name': '捷運站',
                'verbose_name_plural': '捷運站',
            },
        ),
        migrations.AddField(
            model_name='business',
            name='nearest_station',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nearby_businesses', to='users.metrostation'),
        ),
        migrations.AddIndex(
            model_name='business',
            index=models.Index(fields=['nearest_station', 'distance_to_station'], name='users_busin_nearest_41943e_idx'),
        ),
        migrations.AddIndex(
            model_name='business',
            index=models.Index(fields=['rating', '-rating_count'], name='users_busin_rating_678802_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='metrostation',
            unique_together={('line', 'code')},
        ),
    ]
