# Generated by Django 5.1.7 on 2025-03-08 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_metroline_business_distance_to_station_metrostation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='latitude',
            field=models.DecimalField(decimal_places=16, max_digits=19, verbose_name='緯度'),
        ),
        migrations.AlterField(
            model_name='business',
            name='longitude',
            field=models.DecimalField(decimal_places=16, max_digits=19, verbose_name='經度'),
        ),
        migrations.AlterField(
            model_name='metrostation',
            name='latitude',
            field=models.DecimalField(decimal_places=16, max_digits=19, verbose_name='緯度'),
        ),
        migrations.AlterField(
            model_name='metrostation',
            name='longitude',
            field=models.DecimalField(decimal_places=16, max_digits=19, verbose_name='經度'),
        ),
    ]
