# Generated by Django 5.1.7 on 2025-03-11 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_business_latitude_alter_business_longitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='opening_hours',
            field=models.JSONField(blank=True, null=True, verbose_name='營業時間'),
        ),
        migrations.AlterField(
            model_name='business',
            name='types',
            field=models.JSONField(blank=True, null=True, verbose_name='商家類型'),
        ),
    ]
